export const courses = [
  // Webdesign
  {
    id: 1,
    title: "HTML & CSS Grundlagen",
    description:
      "Lerne die Grundlagen der Webentwicklung mit HTML und CSS – ideal für Einsteiger.",
    duration: "4 Wochen",
    level: "Einsteiger",
    badge: "Zertifikat inklusive",
    category: "Webdesign",
    abschlussart: "Zertifikat „HTML & CSS Grundlagen“",
    unterrichtszeiten:
      "Montag bis Freitag von 8:30 bis 15:35 Uhr (in Wochen mit Feiertagen bis 17:10 Uhr)",
    pruefung:
      "Praxisprojekt: Gestaltung und Umsetzung einer eigenen Webseite mit Präsentation",
    vollzeit: true,
    foerderung:
      "Kostenfrei für dich durch Förderung, z. B. Bildungsgutschein der Agentur für Arbeit",
    technologien: [
      "HTML5",
      "CSS3",
      "Visual Studio Code",
      "Live Server",
      "DevTools",
    ],
    inhalte: [
      "Grundlagen der Webentwicklung",
      "Semantisches HTML – Strukturieren von Inhalten",
      "CSS-Selektoren, Box-Modell und Styling",
      "Layout-Techniken mit Flexbox und CSS Grid",
      "Responsive Webdesign",
      "Einführung in Developer Tools",
      "Praktische Mini-Projekte",
      "Barrierefreies Design und Best Practices",
    ],
    zielgruppe: [
      "Berufsanfänger:innen und Studierende",
      "Quereinsteiger:innen ohne Vorkenntnisse",
      "Designer:innen, die Webkenntnisse aufbauen möchten",
      "Alle, die Webentwicklung von Grund auf lernen möchten",
    ],
  },
  {
    id: 2,
    title: "Responsive Design mit TailwindCSS",
    description: "Erstelle moderne, responsive Layouts mit TailwindCSS.",
    duration: "5 Wochen",
    level: "Fortgeschritten",
    badge: "Praxisnah",
    category: "Webdesign",
    abschlussart: "Zertifikat „Responsive Design mit TailwindCSS“",
    unterrichtszeiten:
      "Montag bis Freitag von 8:30 bis 15:35 Uhr (in Wochen mit Feiertagen bis 17:10 Uhr)",
    pruefung:
      "Praxisprojekt: Gestaltung eines responsiven Weblayouts mit TailwindCSS und Präsentation",
    vollzeit: true,
    foerderung:
      "Kostenfrei für dich durch Förderung, z. B. Bildungsgutschein der Agentur für Arbeit",
    technologien: [
      "TailwindCSS",
      "HTML5",
      "CSS3",
      "PostCSS",
      "Visual Studio Code",
      "Responsive Testing Tools",
    ],
    inhalte: [
      "Einführung in Utility-First CSS mit Tailwind",
      "Responsive Design-Prinzipien und Breakpoints",
      "Flexbox und Grid mit Tailwind umsetzen",
      "Custom Themes und Farbpaletten erstellen",
      "Dark Mode und Mobile-First Design",
      "Animationen und Transitionen mit Tailwind",
      "Aufbau wiederverwendbarer Komponenten",
      "Praxisprojekte zur Entwicklung responsiver Webseiten",
    ],
    zielgruppe: [
      "Frontend-Entwickler:innen mit Grundkenntnissen in HTML und CSS",
      "Webdesigner:innen, die moderne Tools kennenlernen möchten",
      "Personen mit Vorkenntnissen, die professionelle Layouts gestalten möchten",
      "Freelancer:innen und Entwickler:innen, die mit Tailwind durchstarten wollen",
    ],
  },
  {
    id: 3,
    title: "UX/UI Grundlagen",
    description: "Verstehe Nutzerverhalten und entwickle intuitive Interfaces.",
    duration: "4 Wochen",
    level: "Einsteiger",
    badge: "Zertifikat inklusive",
    category: "Webdesign",
    abschlussart: "Zertifikat „UX/UI Design Grundlagen“",
    unterrichtszeiten:
      "Montag bis Freitag von 8:30 bis 15:35 Uhr (in Wochen mit Feiertagen bis 17:10 Uhr)",
    pruefung:
      "Praxisprojekt: Entwicklung eines Prototyps mit Benutzerfeedback und Präsentation",
    vollzeit: true,
    foerderung:
      "Kostenfrei für dich durch Förderung, z. B. Bildungsgutschein der Agentur für Arbeit",
    technologien: [
      "Adobe XD",
      "Figma",
      "Miro",
      "UserZoom",
      "HTML/CSS (grundlegend)",
    ],
    inhalte: [
      "Grundlagen von UX (User Experience) und UI (User Interface)",
      "Psychologie der Nutzerführung und Informationsarchitektur",
      "Personas und User Journeys erstellen",
      "Wireframes und Mockups gestalten",
      "Prototyping und Testing von Benutzeroberflächen",
      "Barrierefreiheit und Usability-Prinzipien",
      "Best Practices für mobile und responsive Interfaces",
      "Feedback-Analyse und iterative Verbesserung",
    ],
    zielgruppe: [
      "Berufsanfänger:innen und kreative Quereinsteiger:innen",
      "Designer:innen, die sich im digitalen Bereich spezialisieren möchten",
      "Webentwickler:innen mit Interesse an UX/UI",
      "Marketing-Fachkräfte und Produktmanager:innen",
    ],
  },
  {
    id: 4,
    title: "Webdesign mit Figma",
    description: "Lerne modernes Webdesign mit Figma-Prototyping.",
    duration: "3 Wochen",
    level: "Einsteiger",
    badge: "Design Fokus",
    category: "Webdesign",
    abschlussart: "Zertifikat „Modernes Webdesign mit Figma“",
    unterrichtszeiten:
      "Montag bis Freitag von 8:30 bis 15:35 Uhr (in Wochen mit Feiertagen bis 17:10 Uhr)",
    pruefung:
      "Praxisarbeit: Erstellung eines vollständigen Website-Prototyps in Figma mit anschließender Präsentation",
    vollzeit: true,
    foerderung:
      "Kostenfrei für dich durch Förderung, z. B. Bildungsgutschein der Agentur für Arbeit",
    technologien: [
      "Figma",
      "Adobe Color",
      "Google Fonts",
      "Design Tokens",
      "Responsives Rasterlayout",
    ],
    inhalte: [
      "Einführung in Figma und Interface-Design",
      "Erstellen von Wireframes, Layouts und UI-Komponenten",
      "Arbeiten mit Designsystemen und Bibliotheken",
      "Farbschemata, Typografie und Bildsprache",
      "Responsive Design direkt im Prototyp",
      "Interaktive Prototypen und Nutzerflüsse",
      "Zusammenarbeit und Feedback im Team (Co-Design)",
      "Export für Entwickler:innen und Übergabe",
    ],
    zielgruppe: [
      "Einsteiger:innen im Webdesign",
      "Grafikdesigner:innen, die digital arbeiten wollen",
      "Marketing- oder Kommunikationsfachkräfte",
      "Produktmanager:innen und Startup-Gründer:innen",
    ],
  },
  // Frontend
  {
    id: 5,
    title: "JavaScript für Fortgeschrittene",
    description:
      "Tauche tiefer in moderne JavaScript-Konzepte ein und baue interaktive Anwendungen.",
    duration: "6 Wochen",
    level: "Fortgeschritten",
    badge: "Top Kurs",
    category: "Frontend",
    abschlussart: "Zertifikat „Fortgeschrittenes JavaScript“",
    unterrichtszeiten:
      "Montag bis Freitag von 8:30 bis 15:35 Uhr (in Wochen mit Feiertagen bis 17:10 Uhr)",
    pruefung:
      "Projektarbeit: Entwicklung einer komplexen Webanwendung mit modernen JavaScript-Techniken",
    vollzeit: true,
    foerderung:
      "Kostenfrei für dich durch Förderung, z. B. Bildungsgutschein der Agentur für Arbeit",
    technologien: [
      "JavaScript (ES6+)",
      "Fetch API & Asynchrone Programmierung",
      "DOM-Interaktion",
      "Modularisierung",
      "Tooling mit Vite/Webpack",
    ],
    inhalte: [
      "Erweiterte JavaScript-Syntax (ES6+)",
      "Asynchrone Programmierung mit Promises und async/await",
      "Arbeiten mit Fetch API und REST-Datenquellen",
      "DOM-Manipulation und Event Handling",
      "Modularisierung und Scope-Management",
      "Fehlerbehandlung und Debugging",
      "Einführung in Unit Testing mit Vitest/Jest",
      "Kleine Framework-Übersicht: React, Vue, Svelte (Einordnung)",
    ],
    zielgruppe: [
      "Frontend-Entwickler:innen mit Grundkenntnissen",
      "Webdesigner:innen mit JavaScript-Basiswissen",
      "Quereinsteiger:innen aus IT oder Medien",
      "Studierende technischer Studiengänge",
    ],
  },
  {
    id: 6,
    title: "React.js Masterclass",
    description:
      "Lerne den Aufbau skalierbarer SPAs mit React, Hooks und React Router.",
    duration: "8 Wochen",
    level: "Experte",
    badge: "Live Training",
    category: "Frontend",
    abschlussart: "Zertifikat „React.js Masterclass“",
    unterrichtszeiten:
      "Montag bis Freitag von 8:30 bis 15:35 Uhr (in Wochen mit Feiertagen bis 17:10 Uhr)",
    pruefung:
      "Projektarbeit: Entwicklung einer voll funktionsfähigen Single-Page-App (SPA) mit React",
    vollzeit: true,
    foerderung:
      "Kostenfrei für dich durch Förderung, z. B. Bildungsgutschein der Agentur für Arbeit",
    technologien: [
      "React",
      "React Hooks",
      "React Router",
      "Vite",
      "Axios",
      "Context API",
      "TailwindCSS",
      "Deployment mit Vercel/Netlify",
    ],
    inhalte: [
      "Grundlagen von React-Komponenten und JSX",
      "State-Management mit useState, useReducer, Context API",
      "Effekte und Lifecycle-Management mit useEffect",
      "Routing mit React Router v6",
      "Formularhandling und Validierung",
      "Zustandsverwaltung auf Anwendungsebene",
      "Verbindung zu APIs mit Axios und Fetch",
      "Deployment und Build-Prozesse",
      "Best Practices & Performanceoptimierung",
    ],
    zielgruppe: [
      "Entwickler:innen mit JavaScript-Erfahrung",
      "Frontend-Profis, die React vertiefen möchten",
      "Studierende technischer Studiengänge",
      "Quereinsteiger:innen im Bereich moderne Webentwicklung",
    ],
  },
  {
    id: 7,
    title: "Vue.js Grundlagen",
    description: "Erstelle reactive Webanwendungen mit dem Vue.js Framework.",
    duration: "6 Wochen",
    level: "Fortgeschritten",
    badge: "Framework Fokus",
    category: "Frontend",
    abschlussart: "Zertifikat „Vue.js Grundlagen“",
    unterrichtszeiten:
      "Montag bis Freitag von 8:30 bis 15:35 Uhr (in Wochen mit Feiertagen bis 17:10 Uhr)",
    pruefung:
      "Abschlussprojekt: Entwicklung einer Vue-Anwendung mit Komponenten, Routing und API-Anbindung",
    vollzeit: true,
    foerderung:
      "Kostenfrei für dich durch Förderung, z. B. Bildungsgutschein der Agentur für Arbeit",
    technologien: [
      "Vue.js 3",
      "Composition API",
      "Vue Router",
      "Pinia",
      "Axios",
      "Vite",
      "TailwindCSS",
    ],
    inhalte: [
      "Grundlagen der Vue-Komponentenstruktur",
      "Reaktivität mit der Composition API",
      "Props, Emits und Custom Events",
      "State-Management mit Pinia",
      "Routing und Navigation mit Vue Router",
      "Datenbindung und Formularhandling",
      "API-Integration mit Axios",
      "Modulares Projektsetup mit Vite",
      "Best Practices in Vue-Projekten",
    ],
    zielgruppe: [
      "Webentwickler:innen mit Grundkenntnissen in JavaScript",
      "Frontend-Entwickler:innen, die in Vue.js einsteigen möchten",
      "Studierende mit Fokus auf moderne Webtechnologien",
      "Quereinsteiger:innen mit soliden Programmierkenntnissen",
    ],
  },
  {
    id: 8,
    title: "TypeScript für JavaScript-Entwickler",
    description:
      "Lerne Typsicherheit und moderne Entwicklungspraktiken mit TypeScript.",
    duration: "5 Wochen",
    level: "Fortgeschritten",
    badge: "Code Sicherheit",
    category: "Frontend",
    abschlussart: "Zertifikat „TypeScript für JavaScript-Entwickler“",
    unterrichtszeiten:
      "Montag bis Freitag von 8:30 bis 15:35 Uhr (in Wochen mit Feiertagen bis 17:10 Uhr)",
    pruefung:
      "Abschlussprojekt: Entwicklung einer TypeScript-basierten Webanwendung mit Fokus auf Typisierung und Modularisierung",
    vollzeit: true,
    foerderung:
      "Kostenfrei für dich durch Förderung, z. B. Bildungsgutschein der Agentur für Arbeit",
    technologien: [
      "TypeScript",
      "ESNext",
      "tsconfig",
      "Type Declarations",
      "Visual Studio Code",
      "Node.js",
    ],
    inhalte: [
      "Einführung in TypeScript und Vorteile gegenüber JavaScript",
      "Primitive Typen, Interfaces und Enums",
      "Union & Intersection Types",
      "Generics und Utility Types",
      "Modularisierung & Namespaces",
      "Fehlermanagement und Debugging",
      "TypeScript im Zusammenspiel mit React oder Node.js",
      "Best Practices für große Codebases",
      "Konfiguration und Kompilierung mit tsconfig",
    ],
    zielgruppe: [
      "JavaScript-Entwickler:innen, die ihre Codequalität verbessern möchten",
      "Frontend- oder Backend-Developer mit Interesse an typisierten Sprachen",
      "Teams, die skalierbare Projekte mit TypeScript planen",
      "Programmierer:innen, die professionell in TypeScript einsteigen wollen",
    ],
  },
  // Backend
  {
    id: 9,
    title: "Node.js Einführung",
    description: "Serverseitige Entwicklung mit Node.js und Express.",
    duration: "6 Wochen",
    level: "Einsteiger",
    badge: "Backend Basics",
    category: "Backend",
    abschlussart: "Zertifikat „Node.js Backend-Grundlagen“",
    unterrichtszeiten:
      "Montag bis Freitag von 8:30 bis 15:35 Uhr (in Wochen mit Feiertagen bis 17:10 Uhr)",
    pruefung:
      "Projektarbeit: Entwicklung einer einfachen serverseitigen Anwendung mit REST-API und Präsentation",
    vollzeit: true,
    foerderung:
      "Kostenfrei für dich durch Förderung, z. B. Bildungsgutschein der Agentur für Arbeit",
    technologien: [
      "Node.js",
      "Express.js",
      "npm",
      "REST",
      "Middleware",
      "Postman",
    ],
    inhalte: [
      "Grundlagen der serverseitigen Entwicklung mit JavaScript",
      "Einrichtung und Strukturierung eines Node.js-Projekts",
      "Arbeiten mit npm und externen Modulen",
      "Erstellen von HTTP-Servern mit Express",
      "Routing und Middleware verstehen",
      "RESTful API-Grundlagen",
      "Fehlermanagement und Logging",
      "Erste Anbindung an Datenbanken (z. B. MongoDB oder JSON-Dateien)",
      "Testen und Dokumentieren von APIs mit Postman",
    ],
    zielgruppe: [
      "Einsteiger:innen in die Backend-Entwicklung",
      "Frontend-Entwickler:innen, die serverseitige Grundlagen lernen möchten",
      "Quereinsteiger:innen mit Programmiererfahrung",
      "Teilnehmer:innen technischer Umschulungen oder Weiterbildungen",
    ],
  },
  {
    id: 10,
    title: "Datenbanken mit MongoDB",
    description: "Moderne NoSQL-Datenbankentwicklung mit MongoDB.",
    duration: "4 Wochen",
    level: "Einsteiger",
    badge: "NoSQL Fokus",
    category: "Backend",
    abschlussart: "Zertifikat „Datenbanken mit MongoDB“",
    unterrichtszeiten:
      "Montag bis Freitag von 8:30 bis 15:35 Uhr (in Wochen mit Feiertagen bis 17:10 Uhr)",
    pruefung:
      "Projektarbeit: Modellierung und Umsetzung einer realistischen Datenbanklösung mit Präsentation",
    vollzeit: true,
    foerderung:
      "Kostenfrei für dich durch Förderung, z. B. Bildungsgutschein der Agentur für Arbeit",
    technologien: [
      "MongoDB",
      "MongoDB Compass",
      "Mongoose (Node.js)",
      "Aggregation Framework",
      "NoSQL Design Patterns",
    ],
    inhalte: [
      "Einführung in NoSQL und Unterschiede zu relationalen Datenbanken",
      "Installation und Grundkonfiguration von MongoDB",
      "Datenmodellierung und Schemalosigkeit verstehen",
      "CRUD-Operationen mit MongoDB",
      "Arbeiten mit dem MongoDB Shell und GUI-Tools (Compass)",
      "Datenvalidierung und Indexierung",
      "Aggregation Framework für Auswertungen",
      "Einbindung von MongoDB in Webanwendungen mit Mongoose",
      "Backup- und Restore-Strategien",
    ],
    zielgruppe: [
      "Einsteiger:innen in die Datenbankentwicklung",
      "Webentwickler:innen mit Interesse an modernen Backend-Technologien",
      "Quereinsteiger:innen aus verwandten IT-Bereichen",
      "Personen, die praxisnahe Kenntnisse in NoSQL-Datenbanken erwerben möchten",
    ],
  },
  {
    id: 11,
    title: "RESTful APIs mit Express.js",
    description: "Baue skalierbare APIs mit Express.js.",
    duration: "5 Wochen",
    level: "Fortgeschritten",
    badge: "API Spezialist",
    category: "Backend",
    abschlussart: "Zertifikat „RESTful APIs mit Express.js“",
    unterrichtszeiten:
      "Montag bis Freitag von 8:30 bis 15:35 Uhr (in Wochen mit Feiertagen bis 17:10 Uhr)",
    pruefung:
      "Praxisprojekt: Konzeption und Implementierung einer vollständigen API inklusive Dokumentation und Endpunkt-Tests",
    vollzeit: true,
    foerderung:
      "Kostenfrei für dich durch Förderung, z. B. Bildungsgutschein der Agentur für Arbeit",
    technologien: [
      "Node.js",
      "Express.js",
      "Postman",
      "REST-Standards",
      "JWT",
      "Middleware",
    ],
    inhalte: [
      "Grundlagen von REST und HTTP-Standards",
      "Einführung in Express.js und Aufbau eines API-Projekts",
      "Routing und Middleware verstehen und anwenden",
      "Datenvalidierung und Fehlerbehandlung",
      "Integration von Datenbanken in API-Endpunkte",
      "Nutzer-Authentifizierung mit JWT",
      "Sicherheit und CORS-Richtlinien",
      "Testen von APIs mit Postman und automatisierten Tools",
      "Dokumentation von REST-Schnittstellen (z. B. Swagger)",
      "Deployment von APIs auf Cloud-Plattformen",
    ],
    zielgruppe: [
      "Webentwickler:innen mit Grundkenntnissen in JavaScript",
      "Personen, die APIs für moderne Anwendungen erstellen möchten",
      "Backend-Einsteiger:innen mit Interesse an skalierbarer Architektur",
      "Alle, die den Einstieg in professionelle API-Entwicklung suchen",
    ],
  },
  {
    id: 12,
    title: "Authentication mit JWT & OAuth",
    description: "Implementiere sichere Login-Methoden in Webanwendungen.",
    duration: "4 Wochen",
    level: "Fortgeschritten",
    badge: "Sicherheit Fokus",
    category: "Backend",
    abschlussart: "Zertifikat „Authentication mit JWT & OAuth“",
    unterrichtszeiten:
      "Montag bis Freitag von 8:30 bis 15:35 Uhr (in Wochen mit Feiertagen bis 17:10 Uhr)",
    pruefung:
      "Praxisaufgabe: Umsetzung eines Authentifizierungs-Workflows mit sicherem Login und Rollenverwaltung",
    vollzeit: true,
    foerderung:
      "Kostenfrei für dich durch Förderung, z. B. Bildungsgutschein der Agentur für Arbeit",
    technologien: [
      "Node.js",
      "Express.js",
      "JWT (JSON Web Tokens)",
      "OAuth 2.0",
      "bcrypt",
      "Cookies & Sessions",
      "Postman",
    ],
    inhalte: [
      "Einführung in Authentifizierung und Autorisierung",
      "Unterschiede zwischen JWT und OAuth verstehen",
      "Implementierung von Token-basierten Login-Systemen",
      "Refresh Tokens, Expiry & Token-Management",
      "OAuth 2.0 in Verbindung mit Google, GitHub und anderen Diensten",
      "Absicherung von Routen und geschützten Bereichen",
      "Passwort-Hashing mit bcrypt",
      "Verwaltung von Nutzerrollen und Berechtigungen",
      "Fehler- und Sicherheitsmanagement",
      "Best Practices für Authentifizierungsprozesse",
    ],
    zielgruppe: [
      "Entwickler:innen mit JavaScript- und Node.js-Kenntnissen",
      "Personen, die sichere Login-Systeme implementieren möchten",
      "Backend-Entwickler:innen mit Fokus auf Websicherheit",
      "Alle, die Authentifizierung professionell umsetzen wollen",
    ],
  },
  // KI - Künstliche Intelligenz
  {
    id: 13,
    title: "Einführung in Künstliche Intelligenz",
    description:
      "Grundlagen und Anwendungsbereiche von KI verständlich erklärt.",
    duration: "4 Wochen",
    level: "Einsteiger",
    badge: "KI Basics",
    category: "KI-Künstliche Intelligenz",
    abschlussart: "Zertifikat „Grundlagen der Künstlichen Intelligenz“",
    unterrichtszeiten:
      "Montag bis Freitag von 8:30 bis 15:35 Uhr (in Wochen mit Feiertagen bis 17:10 Uhr)",
    pruefung:
      "Präsentation eines praxisbezogenen Mini-Projekts zur Anwendung von KI",
    vollzeit: true,
    foerderung:
      "Kostenfrei für dich durch Förderung, z. B. Bildungsgutschein der Agentur für Arbeit",
    technologien: [
      "Python (Basiswissen)",
      "Jupyter Notebooks",
      "Einführung in KI-Tools (z. B. ChatGPT, Midjourney)",
      "Google Teachable Machine",
      "KI-Dashboards & Visualisierung",
    ],
    inhalte: [
      "Was ist Künstliche Intelligenz? Geschichte und Entwicklung",
      "Abgrenzung von KI, Machine Learning und Deep Learning",
      "KI im Alltag und in der Arbeitswelt",
      "Grundlagen neuronaler Netze",
      "Ethische Aspekte & gesellschaftliche Auswirkungen von KI",
      "Datengrundlagen und -qualität",
      "Erstellen einfacher KI-Modelle ohne Code",
      "Bild- und Texterkennung mit KI-Tools",
      "Interaktive Übungen mit No-Code-Plattformen",
      "Einführung in die Arbeit mit KI-gestützten Assistenten",
    ],
    zielgruppe: [
      "Berufseinsteiger:innen und Interessierte ohne Vorkenntnisse",
      "Mitarbeitende, die sich mit KI vertraut machen wollen",
      "Entscheider:innen und Projektverantwortliche im digitalen Bereich",
      "Alle, die verstehen wollen, wie KI unsere Zukunft beeinflusst",
    ],
  },
  {
    id: 14,
    title: "Machine Learning mit Python",
    description: "Trainiere Modelle und analysiere Daten mit Scikit-Learn.",
    duration: "6 Wochen",
    level: "Fortgeschritten",
    badge: "Data Science",
    category: "KI-Künstliche Intelligenz",
    abschlussart: "Zertifikat „Machine Learning mit Python & Scikit-Learn“",
    unterrichtszeiten:
      "Montag bis Freitag von 8:30 bis 15:35 Uhr (in Wochen mit Feiertagen bis 17:10 Uhr)",
    pruefung:
      "Projektarbeit: Entwicklung und Präsentation eines ML-Modells zur Lösung eines realen Datenproblems",
    vollzeit: true,
    foerderung:
      "Kostenfrei für dich durch Förderung, z. B. Bildungsgutschein der Agentur für Arbeit",
    technologien: [
      "Python",
      "Jupyter Notebook",
      "Scikit-Learn",
      "Pandas",
      "Matplotlib",
      "NumPy",
    ],
    inhalte: [
      "Einführung in Machine Learning und Anwendungsfälle",
      "Datenaufbereitung und -analyse mit Pandas und NumPy",
      "Trainings-, Validierungs- und Testdaten",
      "Überwachtes vs. unüberwachtes Lernen",
      "Modelltraining mit Scikit-Learn",
      "Klassifikation, Regression und Clustering",
      "Hyperparameter-Tuning und Cross-Validation",
      "Fehlermessung und Performancebewertung",
      "Visualisierung von ML-Ergebnissen",
      "Best Practices und ethische Aspekte beim Umgang mit Daten",
    ],
    zielgruppe: [
      "Teilnehmer:innen mit soliden Python-Grundkenntnissen",
      "Analyst:innen und Entwickler:innen im Data-Umfeld",
      "Personen, die in die Data Science oder KI-Branche einsteigen möchten",
      "IT-affine Quereinsteiger:innen mit Interesse an datengetriebenem Arbeiten",
    ],
  },
  {
    id: 15,
    title: "Deep Learning mit TensorFlow",
    description: "Erstelle neuronale Netzwerke mit TensorFlow und Keras.",
    duration: "8 Wochen",
    level: "Experte",
    badge: "Deep Learning",
    category: "KI-Künstliche Intelligenz",
    abschlussart: "Zertifikat „Deep Learning mit TensorFlow & Keras“",
    unterrichtszeiten:
      "Montag bis Freitag von 8:30 bis 15:35 Uhr (in Wochen mit Feiertagen bis 17:10 Uhr)",
    pruefung:
      "Abschlussprojekt: Entwicklung und Training eines tiefen neuronalen Netzwerks mit anschließender Präsentation",
    vollzeit: true,
    foerderung:
      "Kostenfrei für dich durch Förderung, z. B. Bildungsgutschein der Agentur für Arbeit",
    technologien: [
      "TensorFlow",
      "Keras",
      "Python",
      "Jupyter Notebook",
      "Google Colab",
      "NumPy",
      "Matplotlib",
    ],
    inhalte: [
      "Einführung in künstliche neuronale Netzwerke",
      "Grundlagen von TensorFlow und Keras",
      "Forward- und Backpropagation",
      "Modellarchitekturen: Dense, CNN, RNN, LSTM",
      "Bild- und Sprachverarbeitung mit Deep Learning",
      "Transfer Learning und vortrainierte Modelle",
      "Modelltraining, Optimierung und Evaluierung",
      "Overfitting und Regularisierungstechniken",
      "GPU-Nutzung und Performanceoptimierung",
      "Best Practices im Deep-Learning-Workflow",
    ],
    zielgruppe: [
      "Erfahrene Python-Entwickler:innen mit Interesse an KI",
      "Data Scientists und Analyst:innen, die sich spezialisieren möchten",
      "Technisch versierte Quereinsteiger:innen mit Vorwissen in Machine Learning",
      "Professionals, die KI-Modelle in realen Projekten implementieren möchten",
    ],
  },
  {
    id: 16,
    title: "NLP und Sprachverarbeitung",
    description: "Verarbeite natürliche Sprache mit modernen ML-Techniken.",
    duration: "5 Wochen",
    level: "Fortgeschritten",
    badge: "Textanalyse",
    category: "KI-Künstliche Intelligenz",
    abschlussart: "Zertifikat „NLP und Sprachverarbeitung“",
    unterrichtszeiten:
      "Montag bis Freitag von 8:30 bis 15:35 Uhr (in Wochen mit Feiertagen bis 17:10 Uhr)",
    pruefung:
      "Projektarbeit: Entwicklung eines NLP-Modells zur Textklassifikation oder Chatbot-Entwicklung mit Präsentation",
    vollzeit: true,
    foerderung:
      "Kostenfrei für dich durch Förderung, z. B. Bildungsgutschein der Agentur für Arbeit",
    technologien: [
      "Python",
      "spaCy",
      "NLTK",
      "Transformers (Hugging Face)",
      "TensorFlow",
      "Scikit-learn",
      "Pandas",
    ],
    inhalte: [
      "Grundlagen der natürlichen Sprachverarbeitung (NLP)",
      "Textaufbereitung: Tokenisierung, Stemming, Lemmatisierung",
      "Wortvektoren: Word2Vec, GloVe, FastText",
      "Textklassifikation und Sentimentanalyse",
      "Named Entity Recognition (NER)",
      "Sequence-to-Sequence Modelle",
      "Transformer-Modelle wie BERT und GPT",
      "Anwendung von Pretrained Models mit Hugging Face",
      "Chatbot-Grundlagen und einfache Konversationsmodelle",
      "Praxisorientierte Mini-Projekte",
    ],
    zielgruppe: [
      "Entwickler:innen mit Interesse an Sprach-KI",
      "Data Scientists, die ihre Fähigkeiten im NLP ausbauen möchten",
      "Quereinsteiger:innen mit ML-Vorkenntnissen",
      "Personen aus den Bereichen Kommunikation, Medien und Linguistik, die in die KI einsteigen möchten",
    ],
  },
  {
    id: 17,
    title: "Computer Vision Grundlagen",
    description:
      "Verstehe wie Computer Bilder erkennen und verarbeiten können.",
    duration: "5 Wochen",
    level: "Fortgeschritten",
    badge: "Vision Fokus",
    category: "KI-Künstliche Intelligenz",
    abschlussart: "Zertifikat „Computer Vision Grundlagen“",
    unterrichtszeiten:
      "Montag bis Freitag von 8:30 bis 15:35 Uhr (in Wochen mit Feiertagen bis 17:10 Uhr)",
    pruefung:
      "Projektarbeit: Entwicklung einer Bildklassifikation oder Objekterkennung mit Präsentation der Ergebnisse",
    vollzeit: true,
    foerderung:
      "Kostenfrei für dich durch Förderung, z. B. Bildungsgutschein der Agentur für Arbeit",
    technologien: [
      "Python",
      "OpenCV",
      "TensorFlow",
      "Keras",
      "NumPy",
      "Matplotlib",
      "YOLO",
      "Convolutional Neural Networks (CNNs)",
    ],
    inhalte: [
      "Einführung in Computer Vision und Bildverarbeitung",
      "Bildformate, Kanäle und Farbräume",
      "Grundlegende Bildmanipulation mit OpenCV",
      "Kantenerkennung, Filter und Transformationen",
      "Feature Detection und Matching",
      "Convolutional Neural Networks (CNNs)",
      "Bildklassifikation und Segmentierung",
      "Objekterkennung mit YOLO",
      "Transfer Learning mit vortrainierten Modellen",
      "Projektorientierte Übungen mit realen Bildern",
    ],
    zielgruppe: [
      "Einsteiger:innen mit Interesse an visueller KI",
      "Softwareentwickler:innen mit ML-Grundkenntnissen",
      "Data Scientists, die sich im Bereich Bildverarbeitung spezialisieren möchten",
      "Technikbegeisterte aus dem Bereich Medien, Medizin oder Automatisierung",
    ],
  },
  // Extra Kurse
  {
    id: 18,
    title: "DevOps Grundlagen",
    description: "Verstehe CI/CD, Container und Deployment in modernen Teams.",
    duration: "5 Wochen",
    level: "Einsteiger",
    badge: "Toolchain Einführung",
    category: "Backend",
    abschlussart: "Zertifikat „DevOps Grundlagen“",
    unterrichtszeiten:
      "Montag bis Freitag von 8:30 bis 15:35 Uhr (in Wochen mit Feiertagen bis 17:10 Uhr)",
    pruefung:
      "Abschlussprojekt: Aufbau einer CI/CD-Pipeline mit Containerisierung und automatischem Deployment",
    vollzeit: true,
    foerderung:
      "Kostenfrei für dich durch Förderung, z. B. Bildungsgutschein der Agentur für Arbeit",
    technologien: [
      "Docker",
      "Git & GitHub",
      "GitLab CI/CD",
      "Jenkins",
      "Kubernetes (Grundlagen)",
      "Bash Scripting",
      "YAML",
      "VS Code",
    ],
    inhalte: [
      "Grundlagen von DevOps und agilem Arbeiten",
      "Versionskontrolle mit Git & GitHub",
      "Einführung in CI/CD-Konzepte",
      "Erstellen und Verwalten von Docker-Containern",
      "Continuous Integration mit GitHub Actions oder GitLab CI",
      "Automatisiertes Testing und Deployment",
      "Konfigurationsmanagement mit YAML",
      "Grundlagen zu Kubernetes und Containerorchestrierung",
      "Monitoring und Logging von Deployments",
      "Praxisprojekt mit Echtzeit-Deployment",
    ],
    zielgruppe: [
      "IT-Einsteiger:innen mit Interesse an DevOps-Prozessen",
      "Quereinsteiger:innen in die Systemadministration oder Entwicklung",
      "Softwareentwickler:innen, die Deployment und Automation verstehen möchten",
      "Alle, die moderne Softwarebereitstellung in Teams verstehen wollen",
    ],
  },
  {
    id: 19,
    title: "Git & GitHub professionell nutzen",
    description: "Versionskontrolle, Branches und Pull Requests im Team.",
    duration: "3 Wochen",
    level: "Einsteiger",
    badge: "Teamarbeit",
    category: "Frontend",
    abschlussart: "Zertifikat „Professioneller Einsatz von Git & GitHub“",
    unterrichtszeiten:
      "Montag bis Freitag von 8:30 bis 15:35 Uhr (in Wochen mit Feiertagen bis 17:10 Uhr)",
    pruefung:
      "Abschlussprojekt: Entwicklung und Versionskontrolle eines Projekts mit Feature-Branches und Pull Requests",
    vollzeit: true,
    foerderung:
      "Kostenfrei für dich durch Förderung, z. B. Bildungsgutschein der Agentur für Arbeit",
    technologien: [
      "Git",
      "GitHub",
      "VS Code",
      "GitHub Desktop",
      "Command Line Tools",
      "Markdown",
    ],
    inhalte: [
      "Grundlagen von Versionskontrolle mit Git",
      "Initialisierung und Klonen von Repositories",
      "Commit-Struktur und sinnvolle Commit-Messages",
      "Branching-Strategien und Feature-Branches",
      "Zusammenführen (Merging) und Konfliktlösung",
      "Arbeiten mit Remote-Repositories (Push, Pull, Fetch)",
      "Pull Requests erstellen und verwalten",
      "Code-Reviews und kollaboratives Arbeiten",
      "Releases und Tags setzen",
      "Best Practices in Teamprojekten mit GitHub",
    ],
    zielgruppe: [
      "Einsteiger:innen in die Web- oder Softwareentwicklung",
      "Teams, die effektiv zusammenarbeiten möchten",
      "Quereinsteiger:innen, die Versionskontrolle verstehen wollen",
      "Designer:innen und Entwickler:innen, die gemeinsam Projekte bearbeiten",
    ],
  },
  {
    id: 20,
    title: "Barrierefreies Webdesign",
    description: "Erstelle Webseiten, die für alle zugänglich sind.",
    duration: "4 Wochen",
    level: "Einsteiger",
    badge: "Accessibility Fokus",
    category: "Webdesign",
    abschlussart: "Zertifikat „Barrierefreies Webdesign“",
    unterrichtszeiten:
      "Montag bis Freitag von 8:30 bis 15:35 Uhr (in Wochen mit Feiertagen bis 17:10 Uhr)",
    pruefung:
      "Abschlussprojekt: Konzeption und Umsetzung einer barrierefreien Website mit anschließender Präsentation",
    vollzeit: true,
    foerderung:
      "Kostenfrei für dich durch Förderung, z. B. Bildungsgutschein der Agentur für Arbeit",
    technologien: [
      "HTML5",
      "ARIA-Rollen",
      "WCAG 2.1",
      "CSS für Accessibility",
      "Screenreader-Testing-Tools",
    ],
    inhalte: [
      "Grundlagen der Barrierefreiheit im Web",
      "Rechtliche Grundlagen (BITV, WCAG, DSGVO)",
      "Semantisches HTML und Zugänglichkeit",
      "Nutzung von ARIA-Rollen zur Erweiterung der Zugänglichkeit",
      "Kontrast, Schriftgrößen und visuelles Design",
      "Navigation per Tastatur und Screenreader",
      "Formulare und interaktive Elemente barrierefrei gestalten",
      "Tools und Tests zur Barrierefreiheitsanalyse",
      "Best Practices und Checklisten zur Umsetzung",
    ],
    zielgruppe: [
      "Webentwickler:innen mit Fokus auf Nutzerfreundlichkeit",
      "Designer:innen, die inklusives Design umsetzen wollen",
      "Quereinsteiger:innen im Bereich Webdesign",
      "Unternehmen, die barrierefreie Online-Angebote bereitstellen möchten",
    ],
  },
  {
    id: 21,
    title: "KI in der Webentwicklung",
    description:
      "Erfahre, wie du GPT, Bilderzeugung und intelligente Empfehlungen in Webanwendungen integrierst.",
    duration: "5 Wochen",
    level: "Fortgeschritten",
    badge: "Hands-On Projekt",
    category: "KI-Künstliche Intelligenz",
    abschlussart: "Zertifikat „KI in der Webentwicklung“",
    unterrichtszeiten:
      "Montag bis Freitag von 8:30 bis 15:35 Uhr (in Wochen mit Feiertagen bis 17:10 Uhr)",
    pruefung:
      "Praxisprojekt: Entwicklung einer Webanwendung mit integrierten KI-Funktionen und Abschlusspräsentation",
    vollzeit: true,
    foerderung:
      "Kostenfrei für dich durch Förderung, z. B. Bildungsgutschein der Agentur für Arbeit",
    technologien: [
      "OpenAI GPT (API)",
      "TensorFlow.js",
      "JavaScript & React",
      "Node.js",
      "Cloud-Dienste für KI (z. B. Google Cloud, Azure AI)",
      "Prompt Engineering",
    ],
    inhalte: [
      "Einführung in KI-Anwendungen im Web",
      "Grundlagen zu GPT und textbasierten Sprachmodellen",
      "Bildgenerierung mit KI-Tools (z. B. DALL·E, Stability AI)",
      "Integration von Chatbots mit GPT",
      "Personalisierte Empfehlungen mit Machine Learning",
      "Prompt Engineering und API-Nutzung",
      "Erstellung interaktiver Web-Frontends mit React",
      "Backend-Integration von KI-Modellen",
      "Ethik und Datenschutz im Umgang mit KI",
    ],
    zielgruppe: [
      "Webentwickler:innen mit Interesse an moderner KI",
      "Frontend- und Fullstack-Entwickler:innen",
      "Digital Creators und Startups mit Fokus auf Innovation",
      "Tech-Enthusiasten, die KI praktisch einsetzen möchten",
    ],
  },
];
